### ISSUE TITLE
Circular Reference error originating from Stackify

### ISSUE THREAD

**Issue by asarav** [stackify/stackify-api-python#15]
My team is utilizing Stackify and Sentry for logging purposes within a Django backend. We are finding that Stackify is generating circular reference errors during logging within the data_to_json function in utils.py. These circular reference errors are then being recorded within Sentry.

To narrow down the problem and rule out the possibility of our code being the cause instead of Stackify, I created a new bare bones Django project with a single endpoint (http://127.0.0.1:8000/logging/) that has a divide by zero error. I have included it as an attachment. I have removed the api keys for Stackify and Sentry in the settings. To reproduce the error, you can place keys of your own within the settings.py.
[stackify-error.zip](https://github.com/stackify/stackify-api-python/files/8118774/stackify-error.zip)

We believe that the reason we are getting the circular reference is due to the WSGIRequest and WSGIResponse referencing each other. We see that there has been a previous attempt to solve the circular reference problem with some exception handling (https://github.com/stackify/stackify-api-python/pull/12), but it does not seem to be a full solution since the if statement in the try catch loop does not handle all cases, and it is possible for the except clause to also throw an exception in utils.py.

**Comment by homiedopie** [comment]
Hi @asarav!

Thank you for reporting! I created a PR #16 that will fix the issue.

If you have something to add on the PR, please feel free to add. We really appreciate it!

**Comment by asarav** [comment]
Hi @homiedopie ,
Thanks for the update.
We have tested the PR in our dev environment and locally and it works for us.
The changes make sense to me.

**Comment by homiedopie** [comment]
@asarav - Yes it will be included. Thanks for reporting the issue!

**Comment by homiedopie** [comment]
Released 1.2.0 - https://pypi.org/project/stackify-api-python/1.2.0

Marking as solved
